config/routes.rb
Rails.application.routes.draw do

  resources :locations
  get 'forecast/forecasting'

  root 'dashboard#index', as: 'dashboard_index'
  resources :calls
  resources :employees
  resources :members
  resources :prospects
  resources :class_attendances
  resources :class_times
  resources :membership_types

  post '/convert_to_member', to: 'prospects#convert_to_member', as: 'convert_to_member'
  post '/did_show', to: 'prospects#did_show', as: 'did_show'
  post '/record_calls', to: 'calls#record_calls', as: 'record_calls'
  post '/dash_record_attendance', to: 'class_times#dash_record_attendance', as: 'dash_record_attendance'
  post '/employees/reactivate', to: 'employees#reactivate', as: 'reactivate'
  post '/class_times/reactivate', to: 'class_times#reactivate', as: 'reactivate_ct'
  post '/membership_types/reactivate', to: 'membership_types#reactivate', as: 'reactivate_mt'
  # post '/class_attendances/from_dashboard', to: 'class_attendances#dashboard', as: 'attendance_from_dash'
  get '/convert', to: 'prospects#convert', as: 'convert_prospect'
  get '/prospects/find_no_shows/:showed', to: 'prospects#find_no_shows', as: 'find_no_shows'
  get '/forecast', to: 'forecast#index', as: 'forecast_path'
  get '/dashboard', to: 'dashboard#index', as: 'dashboard_path'
  get '/reports', to: 'reports#index', as: 'reports_path'
  get '/management', to: 'management#index', as: 'management_path'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :calls

  def soft_delete
    self.deleted_at = Date.today
    self.save!
  end

  def reactivate
    self.deleted_at = nil
    self.save!
  end

  def full_name
    full_name = self.fname + ' ' + self.lname
    if self.deleted_at != nil
      full_name = full_name + ' (INACTIVE)'
    end
    return full_name
  end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.where("deleted_at IS NULL")
    @deleted_employees = Employee.where("deleted_at IS NOT NULL")
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.soft_delete
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Soft delete performed on employee.' }
      format.json { head :no_content }
    end
  end

  def reactivate
    @employee = Employee.find(params[:id])
    @employee.reactivate
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:fname, :lname)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul id="error_bg">
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fname, 'First Name' %>
    <%= form.text_field :fname, id: :employee_fname %>
  </div>

  <div class="field">
    <%= form.label :lname, 'Last Name' %>
    <%= form.text_field :lname, id: :employee_lname %>
  </div>
<p></p>
  <div class="actions">
    <%= form.submit nil, :class => 'submit' %>

  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>
<fieldset class="new_employee_fieldset">

<%= render 'form', employee: @employee %>
<p></p>

<%= link_to '<button id="new"> Show </button>'.html_safe, @employee %> &nbsp;&nbsp;&nbsp;
<%= link_to '<button id="new"> Back </button>' .html_safe, employees_path %>
</fieldset>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employees</h1>

<div class="tooltip"><%= image_tag("help.png", width: '15px') %>Help
  <span class="tooltiptext">
    <p>New Employee - create new employee</p>
    <p>Show - show row specific employee</p>
    <p>Edit - edit row specific employee</p>
    <p>Delete - delete row specific employee</p>
  </span>
</div>

<p><%= link_to '<button id="new">New Employee</button>'.html_safe, new_employee_path %></p>

<table id="members">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.fname %></td>
        <td><%= employee.lname %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Delete', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <% @deleted_employees.each do |de| %>
      <tr style="background-color:lightcoral;">
        <td><%= de.fname %></td>
        <td><%= de.lname %> (INACTIVE)</td>
        <td><%= link_to 'Show', de %></td>
        <td><%= link_to 'Edit', edit_employee_path(de) %></td>
        <td><%= link_to '<button id="new">Reactivate</button>'.html_safe, reactivate_path(:id => de.id), method: :post %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/employees/new.html.erb
<h1>New Employee</h1>
<fieldset class="new_employee_fieldset">
<%= render 'form', employee: @employee %>

  <%= link_to '<button id="back">Back</button>'.html_safe, employees_path %>
</fieldset>

app/views/employees/reactivate.html.erb
<h2>Employee has been reactivated</h2><br>


<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Employee</h1>

<fieldset class="show_employee_fieldset">

<p>
  <strong>First Name:</strong>
  <%= @employee.fname %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @employee.lname %>
</p>
<br>
<%= link_to '<button id="new"> Edit </button>' .html_safe, edit_employee_path(@employee) %> &nbsp;&nbsp;&nbsp;
<%= link_to '<button id="new"> Back </button>' .html_safe, employees_path %>
</fieldset>