config/routes.rb
Rails.application.routes.draw do

  resources :locations
  get 'forecast/forecasting'

  root 'dashboard#index', as: 'dashboard_index'
  resources :calls
  resources :employees
  resources :members
  resources :prospects
  resources :class_attendances
  resources :class_times
  resources :membership_types

  post '/convert_to_member', to: 'prospects#convert_to_member', as: 'convert_to_member'
  post '/did_show', to: 'prospects#did_show', as: 'did_show'
  post '/record_calls', to: 'calls#record_calls', as: 'record_calls'
  post '/dash_record_attendance', to: 'class_times#dash_record_attendance', as: 'dash_record_attendance'
  post '/employees/reactivate', to: 'employees#reactivate', as: 'reactivate'
  post '/class_times/reactivate', to: 'class_times#reactivate', as: 'reactivate_ct'
  post '/membership_types/reactivate', to: 'membership_types#reactivate', as: 'reactivate_mt'
  # post '/class_attendances/from_dashboard', to: 'class_attendances#dashboard', as: 'attendance_from_dash'
  get '/convert', to: 'prospects#convert', as: 'convert_prospect'
  get '/prospects/find_no_shows/:showed', to: 'prospects#find_no_shows', as: 'find_no_shows'
  get '/forecast', to: 'forecast#index', as: 'forecast_path'
  get '/dashboard', to: 'dashboard#index', as: 'dashboard_path'
  get '/reports', to: 'reports#index', as: 'reports_path'
  get '/management', to: 'management#index', as: 'management_path'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/membership_types_controller.rb
class MembershipTypesController < ApplicationController
  before_action :set_membership_type, only: [:show, :edit, :update, :destroy]

  # GET /membership_types
  # GET /membership_types.json
  def index
    @membership_types = MembershipType.where("deleted_at IS NULL")
    @deleted_types = MembershipType.where("deleted_at IS NOT NULL")
  end

  # GET /membership_types/1
  # GET /membership_types/1.json
  def show
  end

  # GET /membership_types/new
  def new
    @membership_type = MembershipType.new
  end

  # GET /membership_types/1/edit
  def edit
  end

  # POST /membership_types
  # POST /membership_types.json
  def create
    @membership_type = MembershipType.new(membership_type_params)

    respond_to do |format|
      if @membership_type.save
        format.html { redirect_to @membership_type, notice: 'Membership type was successfully created.' }
        format.json { render :show, status: :created, location: @membership_type }
      else
        format.html { render :new }
        format.json { render json: @membership_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /membership_types/1
  # PATCH/PUT /membership_types/1.json
  def update
    respond_to do |format|
      if @membership_type.update(membership_type_params)
        format.html { redirect_to @membership_type, notice: 'Membership type was successfully updated.' }
        format.json { render :show, status: :ok, location: @membership_type }
      else
        format.html { render :edit }
        format.json { render json: @membership_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /membership_types/1
  # DELETE /membership_types/1.json
  def destroy
    @membership_type.soft_delete
    respond_to do |format|
      format.html { redirect_to membership_types_url, notice: 'Soft delete performed on Membership Type.' }
      format.json { head :no_content }
    end
  end

  def reactivate
    @membership_type = MembershipType.find(params[:id])
    @membership_type.reactivate
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_membership_type
      @membership_type = MembershipType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def membership_type_params
      params.require(:membership_type).permit(:membership_type)
    end
end

app/helpers/membership_types_helper.rb
module MembershipTypesHelper
end

app/views/membership_types/_form.html.erb
<%= form_with(model: membership_type, local: true) do |form| %>
  <% if membership_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(membership_type.errors.count, "error") %> prohibited this membership_type from being saved:</h2>

      <ul id="error_bg">
      <% membership_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <b><%= form.label :membership_type, 'Type' %></b>
    <%= form.text_field :membership_type, id: :membership_type %>
  </div>
<p></p>
  <div class="actions">
    <%= form.submit nil, :class => 'submit' %>

  </div>
<% end %>

app/views/membership_types/edit.html.erb
<h1>Editing Membership Type</h1>
<fieldset class="new_membership_fieldset">

<%= render 'form', membership_type: @membership_type %>

<%= link_to '<button id="new"> Show </button>'.html_safe, @membership_type %> &nbsp;&nbsp;&nbsp;
<%= link_to '<button id="new"> Back </button>'.html_safe, membership_types_path %>
</fieldset>

app/views/membership_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Membership Types</h1>

<div class="tooltip"><%= image_tag("help.png", width: '15px') %>Help
  <span class="tooltiptext">
    <p>New Membership Type - create new membership type</p>
    <p>Show - show row specific membership type</p>
    <p>Edit - edit row specific membership type</p>
    <p>Delete - delete row specific membership type</p>
  </span>
</div>

<p><%= link_to '<button id="new">New Membership Type</button>'.html_safe, new_membership_type_path %></p>

<table id="members">
  <thead>
    <tr>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="actions">
    <% @membership_types.each do |membership_type| %>
      <tr>
        <td><%= membership_type.membership_type %></td>
        <td><%= link_to 'Show', membership_type %></td>
        <td><%= link_to 'Edit', edit_membership_type_path(membership_type) %></td>
        <td><%= link_to 'Delete', membership_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <% @deleted_types.each do |dt| %>
    <tr style="background-color:lightcoral;">
      <td><%= dt.membership_type %> (INACTIVE)</td>
      <td><%= link_to 'Show', dt %></td>
      <td><%= link_to 'Edit', edit_membership_type_path(dt) %></td>
      <td><%= link_to '<button id="new">Reactivate</button>'.html_safe, reactivate_mt_path(:id => dt.id), method: :post %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/membership_types/new.html.erb
<h1>New Membership Type</h1>
<fieldset class="new_membership_fieldset">
<%= render 'form', membership_type: @membership_type %>

  <%= link_to '<button id="back">Back</button>'.html_safe, membership_types_path %>
</fieldset>

app/views/membership_types/reactivate.html.erb
<h2>Membership Type has been reactivated</h2><br>


<%= link_to 'Back', membership_types_path %>

app/views/membership_types/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Membership Type</h1>

<fieldset class="show_membership_fieldset">

<p>
  <strong>Type:</strong>
  <%= @membership_type.membership_type %>
</p>
<br>
<%= link_to '<button id="new"> Edit </button>' .html_safe, edit_membership_type_path(@membership_type) %> &nbsp;&nbsp;&nbsp;
<%= link_to '<button id="back"> Back </button>' .html_safe, membership_types_path %>
</fieldset>