config/routes.rb
Rails.application.routes.draw do

  resources :locations
  get 'forecast/forecasting'

  root 'dashboard#index', as: 'dashboard_index'
  resources :calls
  resources :employees
  resources :members
  resources :prospects
  resources :class_attendances
  resources :class_times
  resources :membership_types

  post '/convert_to_member', to: 'prospects#convert_to_member', as: 'convert_to_member'
  post '/did_show', to: 'prospects#did_show', as: 'did_show'
  post '/record_calls', to: 'calls#record_calls', as: 'record_calls'
  post '/dash_record_attendance', to: 'class_times#dash_record_attendance', as: 'dash_record_attendance'
  post '/employees/reactivate', to: 'employees#reactivate', as: 'reactivate'
  post '/class_times/reactivate', to: 'class_times#reactivate', as: 'reactivate_ct'
  post '/membership_types/reactivate', to: 'membership_types#reactivate', as: 'reactivate_mt'
  # post '/class_attendances/from_dashboard', to: 'class_attendances#dashboard', as: 'attendance_from_dash'
  get '/convert', to: 'prospects#convert', as: 'convert_prospect'
  get '/prospects/find_no_shows/:showed', to: 'prospects#find_no_shows', as: 'find_no_shows'
  get '/forecast', to: 'forecast#index', as: 'forecast_path'
  get '/dashboard', to: 'dashboard#index', as: 'dashboard_path'
  get '/reports', to: 'reports#index', as: 'reports_path'
  get '/management', to: 'management#index', as: 'management_path'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/call.rb
class Call < ApplicationRecord
  belongs_to :member
  belongs_to :employee
  
  def record_call(emp_id, outcome)
    self.update(employee: emp_id, outcome: outcome, completed: Date.today)
  end

  def is_completed
    if self.completed.nil?
      return "Not completed"
    else
      return "Completed"
    end
  end

  def outcomes
    return ["Left Message", "Spoke to Someone"]
  end

end

app/controllers/calls_controller.rb
class CallsController < ApplicationController
  before_action :set_call, only: [:show, :edit, :update, :destroy]

  # GET /calls
  # GET /calls.json
  def index
    # @calls = Call.paginate(:page => params[:page], per_page: 20)


    if params[:filter] == "All Calls"
      @calls = Call.paginate(:page => params[:page], per_page: 20)
      @view_type = "All "
    elsif params[:filter] == "Past Due"
      @calls = Call.where("due_date < ? AND completed IS NULL", "#{Date.today}").paginate(:page => params[:page], per_page: 20)
      @view_type = "Past Due "
    else
      @calls = Call.where("due_date > ? AND completed IS NULL", "#{Date.today}").paginate(:page => params[:page], per_page: 20)
      @view_type = "Upcoming "
    end
  end

  def record_calls
    @call = Call.find(params[:id])
    @call.record_call(params[:employee_id], params[:outcome])
    redirect_to request.referrer, notice: "Call recorded"
  end


  # GET /calls/1
  # GET /calls/1.json
  def show
  end

  # GET /calls/new
  def new
    @call = Call.new
  end

  # GET /calls/1/edit
  def edit
  end

  # POST /calls
  # POST /calls.json
  def create
    @call = Call.new(call_params)

    respond_to do |format|
      if @call.save
        format.html { redirect_to @call, notice: 'Call was successfully created.' }
        format.json { render :show, status: :created, location: @call }
      else
        format.html { render :new }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calls/1
  # PATCH/PUT /calls/1.json
  def update
    respond_to do |format|
      if @call.update(call_params)
        format.html { redirect_to @call, notice: 'Call was successfully updated.' }
        format.json { render :show, status: :ok, location: @call }
      else
        format.html { render :edit }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calls/1
  # DELETE /calls/1.json
  def destroy
    @call.destroy
    respond_to do |format|
      format.html { redirect_to calls_url, notice: 'Call was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_call
      @call = Call.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def call_params
      params.require(:call).permit(:member_id, :employee_id, :outcome, :due_date, :completed, :filter)
    end
end

app/helpers/calls_helper.rb
module CallsHelper
end

app/views/calls/_form.html.erb
<%= form_with(model: call, local: true) do |form| %>
  <% if call.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(call.errors.count, "error") %> prohibited this call from being saved:</h2>

      <ul id="error_bg">
      <% call.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :member_id %>
    <%= form.collection_select :member_id, Member.all, :id, :fname %>
  </div>

  <div class="field">
    <%= form.label :employee_id %>
    <%= form.collection_select :employee_id, Employee.where("deleted_at IS NULL"), :id, :full_name %>
  </div>

  <div class="field">
    <%= form.label :outcome %>
    <%= form.select :outcome, ['Left Message', 'Spoke to Someone'] %>
  </div>

  <div class="field">
    <%= form.label :due_date, 'Due Date' %>
    <%= form.date_select :due_date, id: :call_due_date %>
  </div>

  <div class="field">
    <%= form.label :completed %>
    <%= form.date_select :completed, id: :call_completed %>
  </div>
<p></p>
  <div class="actions">
    <%= form.submit nil, :class => 'submit' %>

  </div>
<% end %>

app/views/calls/edit.html.erb
<h1>Editing Call</h1>
<div class="fieldset">
<%= render 'form', call: @call %>

  <p></p>
<%= link_to ' <button id="new"> Show </button>'.html_safe,  @call %> &nbsp;&nbsp;&nbsp;
<%= link_to '<button id="new"> Back </button>'.html_safe, request.referrer, notice: "Call recorded" %>
</div>

app/views/calls/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @view_type %>Calls</h1>

<div class="tooltip"><%= image_tag("help.png", width: '15px') %>Help
  <span class="tooltiptext">
    <p>New Call - create new call</p>
    <p>Upcoming - show list of upcoming calls</p>
    <p>All Calls - show list of all calls</p>
    <p>Past Due - show list of past due calls</p>
    <p>Record Check-in Call - edit row specific call</p>
    <p>Delete - delete row specific call</p>
  </span>
</div>

<p><%= link_to '<button id="new">New Call</button>'.html_safe, new_call_path %></p>

<span>
  <%= form_tag(calls_path, method: :get) do %>
    <p><b>Filter Search</b></p>
    <%= submit_tag 'Upcoming', name: "filter", :class => 'search' %> &nbsp;
    <%= submit_tag 'All Calls', name: "filter", :class => 'search' %> &nbsp;
    <%= submit_tag 'Past Due', name: "filter", :class => 'search' %>
  <% end %>
</span>
<br>

<table id="calls">
  <thead>
    <tr>
      <th>Member</th>
      <th>Phone Number</th>
      <th>Employee</th>
      <th>Due Date</th>
      <th>Completed</th>
      <th>Outcome</th>
      <th colspan="3">Manage Calls</th>
    </tr>
  </thead>

  <tbody>
    <% @calls.each do |call| %>
      <tr>
        <td><%= call.member.full_name %></td>
        <td><%= call.member.phone_number %></td>
        <td><%= call.employee.fname %></td>
        <td><%= call.due_date %></td>
        <td><%= call.completed %></td>
        <td><%= call.outcome %></td>
        <td><%= link_to '<button id="new">Record Check-in Call</button>'.html_safe, edit_call_path(call) %></td>
        <td><%= link_to 'Delete', call, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<div class="pagination">
  <div class="page_info">
    <%= page_entries_info @call %>
  </div>
  <%= will_paginate @call, :container => false %>
</div>

app/views/calls/new.html.erb
<h1>New Call</h1>
<div class="fieldset">
<%= render 'form', call: @call %>

  <%= link_to '<button id="back">Back</button>'.html_safe, calls_path %>
</div>

app/views/calls/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Call</h1>

<fieldset class="show_call_fieldset">

<p>
  <strong>Member:</strong>
  <%= @call.member.full_name %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @call.employee.fname %>
</p>

<p>
  <strong>Outcome:</strong>
  <%= @call.outcome %>
</p>

<p>
  <strong>Due Date:</strong>
  <%= @call.due_date %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @call.completed %>
</p>
  <br>

<%= link_to '<button id="new"> Edit </button>'.html_safe, edit_call_path(@call) %> &nbsp;&nbsp;&nbsp;
<%= link_to '<button id="new"> Back </button>'.html_safe, dashboard_index_path %>
</fieldset>