config/routes.rb
Rails.application.routes.draw do

  resources :locations
  get 'forecast/forecasting'

  root 'dashboard#index', as: 'dashboard_index'
  resources :calls
  resources :employees
  resources :members
  resources :prospects
  resources :class_attendances
  resources :class_times
  resources :membership_types

  post '/convert_to_member', to: 'prospects#convert_to_member', as: 'convert_to_member'
  post '/did_show', to: 'prospects#did_show', as: 'did_show'
  post '/record_calls', to: 'calls#record_calls', as: 'record_calls'
  post '/dash_record_attendance', to: 'class_times#dash_record_attendance', as: 'dash_record_attendance'
  post '/employees/reactivate', to: 'employees#reactivate', as: 'reactivate'
  post '/class_times/reactivate', to: 'class_times#reactivate', as: 'reactivate_ct'
  post '/membership_types/reactivate', to: 'membership_types#reactivate', as: 'reactivate_mt'
  # post '/class_attendances/from_dashboard', to: 'class_attendances#dashboard', as: 'attendance_from_dash'
  get '/convert', to: 'prospects#convert', as: 'convert_prospect'
  get '/prospects/find_no_shows/:showed', to: 'prospects#find_no_shows', as: 'find_no_shows'
  get '/forecast', to: 'forecast#index', as: 'forecast_path'
  get '/dashboard', to: 'dashboard#index', as: 'dashboard_path'
  get '/reports', to: 'reports#index', as: 'reports_path'
  get '/management', to: 'management#index', as: 'management_path'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/class_time.rb
class ClassTime < ApplicationRecord
  has_many :prospects
  has_many :class_attendances, :dependent => :destroy
  accepts_nested_attributes_for :class_attendances


  def soft_delete
    self.deleted_at = Date.today
    self.save!
  end

  def reactivate
    self.deleted_at = nil
    self.save!
  end

  def class_and_time
    #this function returns the ClassTime record in the business's
    # vernacular.  In order for the customers to use this functionality
    # most intuitively for them, it is important we present the ClassTime
    # records in this format. (ie, "Monday 5:30am")
    class_name = self.day_of_week + " " + self.start_time.strftime('%H:%M')
    if self.deleted_at != nil
      class_name = class_name + ' (INACTIVE)'
    end
    return class_name
  end

  def just_time
    time_of_class = self.start_time.strftime('%H:%M')
    if self.deleted_at != nil
      time_of_class = time_of_class + ' (INACTIVE)'
    end
    return time_of_class
  end

  def forecasted
    one_year = ((class_attendances.first(52).map(&:attendance).sum).to_f / 52).round(1)
    six_month = ((class_attendances.first(24).map(&:attendance).sum).to_f / 24).round(1)
    two_weeks = ((class_attendances.first(2).map(&:attendance).sum).to_f / 2).round(1)

    forecast = (one_year * 0.6) + (six_month * 0.3) + (two_weeks * 0.1)
    return forecast.round(1)

  end

  def record_attendance(attendance)
    new_class = ClassAttendance.create(class_time_id: self.id, date: Date.today(), attendance: attendance)
    new_class.save!
  end

  def temp_attendance
    return 0
  end

  def previous_month_averages(months_back)
    range_start = (Date.today - months_back.month).beginning_of_month
    range_end = (Date.today - months_back.month).end_of_month
    lm_sum = ((class_attendances.where("date BETWEEN ? AND ?", range_start, range_end).map(&:attendance).sum).to_f)
    lm_count = (class_attendances.where("date BETWEEN ? AND ?", range_start, range_end).map().count).to_f
    avg = (lm_sum / lm_count).to_f.round(1)
  end

  def project_next_month
    month_diff = previous_month_averages(1) - previous_month_averages(2)
    projected = forecasted - month_diff.to_f
    return (projected.abs).round(1)
  end


end

app/controllers/class_times_controller.rb
class ClassTimesController < ApplicationController
  before_action :set_class_time, only: [:show, :edit, :update, :destroy]

  # GET /class_times
  # GET /class_times.json
  def index
    # @class_times = ClassTime.all
    @class_times = ClassTime.where("deleted_at IS NULL").paginate(:page => params[:page], per_page: 20)
    @deleted_class_times = ClassTime.where("deleted_at IS NOT NULL")
  end

  # GET /class_times/1
  # GET /class_times/1.json
  def show
  end

  # GET /class_times/new
  def new
    @class_time = ClassTime.new
  end

  def dash_record_attendance
    attendance = params[:attendance]
    ct = ClassTime.find(params[:class_time])
    ct.record_attendance(attendance)
  end

  # GET /class_times/1/edit
  def edit
  end

  # POST /class_times
  # POST /class_times.json
  def create
    @class_time = ClassTime.new(class_time_params)

    respond_to do |format|
      if @class_time.save
        format.html { redirect_to @class_time, notice: 'Class time was successfully created.' }
        format.json { render :show, status: :created, location: @class_time }
      else
        format.html { render :new }
        format.json { render json: @class_time.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /class_times/1
  # PATCH/PUT /class_times/1.json
  def update
    respond_to do |format|
      if @class_time.update(class_time_params)
        format.html { redirect_to @class_time, notice: 'Class time was successfully updated.' }
        format.json { render :show, status: :ok, location: @class_time }
      else
        format.html { render :edit }
        format.json { render json: @class_time.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /class_times/1
  # DELETE /class_times/1.json
  def destroy
    @class_time.soft_delete
    respond_to do |format|
      format.html { redirect_to class_times_url, notice: 'Soft delete performed on Class Time.' }
      format.json { head :no_content }
    end
  end

  def reactivate
    @class_time = ClassTime.find(params[:id])
    @class_time.reactivate
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_class_time
      @class_time = ClassTime.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def class_time_params
      params.require(:class_time).permit(:day_of_week, :start_time)
    end
end

app/helpers/class_times_helper.rb
module ClassTimesHelper
end

app/views/class_times/_form.html.erb
<%= form_with(model: class_time, local: true) do |form| %>
  <% if class_time.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(class_time.errors.count, "error") %> prohibited this class_time from being saved:</h2>

      <ul id="error_bg">
      <% class_time.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :day_of_week, 'Day of Week' %>
    <%= form.text_field :day_of_week, id: :class_time_day_of_week %>
  </div>

  <div class="field">
    <%= form.label :start_time, 'Start Time' %>
    <%= form.time_select :start_time, id: :class_time_start_time %>
  </div>
<p></p>
  <div class="actions">
    <%= form.submit nil, :class => 'submit' %>
  </div>
<% end %>

app/views/class_times/edit.html.erb
<h1>Editing Class Time</h1>
<fieldset class="new_time_fieldset">

<%= render 'form', class_time: @class_time %>

<%= link_to '<button id="new"> Show </button>' .html_safe, @class_time %> &nbsp;&nbsp;&nbsp;
<%= link_to '<button id="new"> Back </button>' .html_safe, class_times_path %>
</fieldset>

app/views/class_times/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Class Times</h1>

<div class="tooltip"><%= image_tag("help.png", width: '15px') %>Help
  <span class="tooltiptext">
    <p>New Class Time - create new class time</p>
    <p>Show - show row specific class time</p>
    <p>Edit - edit row specific class time</p>
    <p>Delete - delete row specific class time</p>
  </span>
</div>

<p><%= link_to '<button id="new">New Class Time</button>'.html_safe, new_class_time_path %></p>

<table id="members">
  <thead>
    <tr>
      <th>Day of Week</th>
      <th>Start Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @class_times.each do |class_time| %>
      <tr>
        <td><%= class_time.day_of_week %></td>
        <td><%= class_time.start_time.strftime('%H:%M') %></td>
        <td><%= link_to 'Show', class_time %></td>
        <td><%= link_to 'Edit', edit_class_time_path(class_time) %></td>
        <td><%= link_to 'Delete', class_time, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <% @deleted_class_times.each do |dct| %>
      <tr style="background-color:lightcoral;">
        <td><%= dct.day_of_week %></td>
        <td><%= dct.start_time.strftime('%H:%M') %></td>
        <td><%= link_to 'Show', dct %></td>
        <td><%= link_to 'Edit', edit_class_time_path(dct) %></td>
        <td><%= link_to '<button id="new">Reactivate</button>'.html_safe, reactivate_ct_path(:id => dct.id), method: :post %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="pagination">
  <div class="page_info">
    <%= page_entries_info @class_time %>
  </div>
  <%= will_paginate @class_time, :container => false %>
</div>

app/views/class_times/new.html.erb
<h1>New Class Time</h1>
<fieldset class="new_time_fieldset">
<%= render 'form', class_time: @class_time %>

  <%= link_to '<button id="back">Back</button>'.html_safe, class_times_path %>
</div>
</fieldset>

app/views/class_times/reactivate.html.erb
<h2>Class Time has been reactivated</h2><br>


<%= link_to 'Back', class_times_path %>

app/views/class_times/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Class Time</h1>

<fieldset class="show_time_fieldset">

<p>
  <strong>Day of Week:</strong>
  <%= @class_time.day_of_week %>
</p>

<p>
  <strong>Start Time:</strong>
  <%= @class_time.start_time %>
</p>
  <br>
<%= link_to '<button id="new"> Edit </button>' .html_safe, edit_class_time_path(@class_time) %> &nbsp;&nbsp;&nbsp;
<%= link_to '<button id="new"> Back </button>' .html_safe, class_times_path %>
</fieldset>